<?php

use Arachne\Bootstrap\Configurator;
use Tracy\Debugger;

// Load autoloader generated by Composer
require __DIR__ . '/../vendor/autoload.php';

// Normalized internal encoding
mb_internal_encoding('UTF-8');

// Normalized locale settings
$locale = 'en_US.UTF-8';
setlocale(LC_ALL, $locale);
putenv('LC_ALL=' . $locale);

$configurator = new Configurator();

$configurator->addParameters([
	'appDir' => __DIR__,
	'wwwDir' => __DIR__ . '/../www',
]);

$configurator->enableDebugger(__DIR__ . '/../log', 'enumag@gmail.com');
Debugger::getLogger()->emailSnooze = '1 hour';

// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon', false);

return $configurator->createContainer();
